### ISSUE TITLE
Give better error when deployment credentials fail

### ISSUE THREAD

**Issue by ManuelDeLeon** [fractal-code/meteor-azure#36]
Just a suggestion, if the deployment fails with a 401, give a message like "Check your deployment credentials (username and password)". Right now it's just "401".
```
info:    Deploying bundle tarball
error:   Request failed with status code 401
```

**Comment by jycouet** [comment]
Actually I checked multiple times my username & password, but I still get 
> debug:   create tarball
> info:    Deploying bundle tarball
> error:   Request failed with status code 401

Could it be something else?

**Comment by ManuelDeLeon** [comment]
I got this error because I deployed a new app and thus followed the setup instructions again. It turns out the deployment credentials are either for the whole account or resource group (haven't bothered to check). In my case I created a new deployment credentials for the new app and deployed it no problem. It failed when I tried to deploy the old one and thus got the 401 error. I now use the same deployment username/password for both apps and life is good.

While technically not an issue with meteor-azure, I think the docs should mention it.

**Comment by jycouet** [comment]
I agree that it's most probably not link directly to meteor-azure.
But I reset the user/password so I'm sure about it and it's still not working. So I guess that it could be also something else?
Maybe I'll try in a new ressource group

**Comment by ramijarrar** [comment]
@ManuelDeLeon It's mentioned in the [Getting started](http://meteor-azure.readthedocs.io/en/latest/getting-started.html#step-2-configure-azure-web-app) tutorial:

> Open “Deployment credentials” and set a username and password (these are applicable to any app in your account)

@jycouet Can you paste the full command output (in debug mode)? Are you targeting a deployment slot? Can you confirm the credentials are being set in this page:

![image](https://user-images.githubusercontent.com/9661116/27888813-8b0931aa-622b-11e7-9670-ed5e1cba19d2.png)

**Comment by jycouet** [comment]
Yes, sure.

- Here is the full output in debug:

> info:    Authenticating with interactive login...
> To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code XXXXXXXXX to authenticate.
> debug:   completed Azure authentication
> info:    Updating Azure application settings
> debug:   set environment variables
> debug:   set Meteor settings
> debug:   set Kudu deployment settings
> debug:   set Node to v4.8.2
> debug:   set NPM to v4.5.0
> info:    Compiling application bundle
> debug:   generate meteor build
> warn:    Using default web config
> debug:   create tarball
> info:    Deploying bundle tarball
> error:   Request failed with status code 401

- I'm not targeting a deployment slot 

- I used the page you linked ("Deployment credentials") to setup my credentials

**Comment by jycouet** [comment]
WoW, I found!
My password was not containing capital letters! Azure didn't say anything about wrong password... ! but it seems not well set.
Now it's working like a charm, thank you.

**Comment by ramijarrar** [comment]
This has been implemented in v2.0.8 with a pre-check.

For reference, expect the following message:

`error:   Could not authenticate with Kudu (check your deployment credentials)`
